plugins {
    id 'java-library'
    id 'iso2t-publishing'
    id 'net.neoforged.moddev'
}

group = rootProject.group

base { archivesName = "${mod_id}-api" }

java {
    toolchain.languageVersion = JavaLanguageVersion.of(java_version)
    withSourcesJar()
    withJavadocJar()
}

neoForge { neoFormVersion = neo_form_version }

configurations.create('apiJava') {
    canBeResolved = false
    canBeConsumed = true
}
artifacts { apiJava sourceSets.main.java.sourceDirectories.singleFile }

tasks.withType(Jar).configureEach {
    from(rootProject.file('LICENSE.md')) { rename { "${it}_${mod_name}" } }
}
